import type { Metadata } from "next";
import { Lora, Open_Sans } from 'next/font/google'; // Import Lora and Open_Sans
import "./globals.css";
import StickyHeaderWrapper from "./components/StickyHeaderWrapper";
import Footer from "./components/Footer";
import AOSInitializer from './components/AOSInitializer'; // Import AOSInitializer

// Configure Lora font (for headings and buttons)
const lora = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora', // CSS variable for Lora
  weight: ['400', '500', '600', '700'] // Weights for Lora
});

// Configure Open Sans font (for body text)
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-open-sans', // CSS variable for Open Sans
  weight: ['400', '500', '600', '700'] // Weights for Open Sans
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lora.variable} ${openSans.variable} flex flex-col min-h-screen`}> 
      <body className={`${openSans.className} flex flex-col flex-grow`}> 
        <AOSInitializer /> {/* Initialize AOS */}
        <StickyHeaderWrapper />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
